name: Deploy to GitHub Pages

on:
  # 监听 main 分支的 push 事件，只要你 push 代码，就会触发自动部署
  push:
    branches: [ "main" ]

# 给工作流赋予部署 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 使用稳定的 Node 20 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite 打包出来的产物默认在 dist 文件夹

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4